CREATE DATABASE TankGame;

USE TankGame;

CREATE TABLE `user` (
`username` VARCHAR(12) NOT NULL PRIMARY KEY  ,
`score` INT
) ENGINE=INNODB DEFAULT CHARSET=utf8;


INSERT INTO USER VALUES('zi',6);
INSERT INTO USER VALUES('su',6);
INSERT INTO USER VALUES('zh',6)